### ISSUE TITLE
When calling /api/drivers/{meeting_name} more than once, I start getting duplicated driver names

### ISSUE THREAD

**Issue by lgodz15** [AlexyCz/F1RadioSentiment#5]
With the more times I call  /api/drivers/{meeting_name}, it seems an extra duplication is made of each of the driver's names. It started with just two instances of each driver name but now I'm up to 5 being returned. 

<img width="332" alt="Screenshot 2024-12-02 at 8 53 45 PM" src="https://github.com/user-attachments/assets/8268777c-6783-44ba-b490-54a058f7d335">

**Comment by AlexyCz** [comment]
Source of issue: [Line 60](https://github.com/AlexyCz/F1RadioSentiment/blob/main/api/src/service.py#L60) in the `service` module.
The drivers need to be filtered on the current session key before returning the list, or else we return all aggregated driver data.
