### ISSUE TITLE
When calling /api/races/driver_data/{driver_name}, getting back some empty string lap_numbers

### ISSUE THREAD

**Issue by lgodz15** [AlexyCz/F1RadioSentiment#6]
When I call /api/races/driver_data/{driver_name}, I'm sometimes getting back radios with an empty string as the `lap_number`, as well as a "NaT" `lap_date_start`.

Since `lap_avg_sentiment` contains the average sentiment for every lap that means I'm also getting a lap sentiment for this empty string lap. See example attached.

[leclerc_2023_canada.json](https://github.com/user-attachments/files/17987625/leclerc_2023_canada.json)

**Comment by AlexyCz** [comment]
In `_set_radio_lap_number` we use [pandas.merge_as_of](https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html), and unfortunately if there is no nearest timestamp, it will fill in an `NaT` for the lap timestamp and an empty string for the lap number.

Possible fix: simply `fillna()` with lap 0 in the lap number column, and session start time stamp for the the lap date start.

We use the default `backward` for the `direction` param:
> A “backward” search selects the last row in the right DataFrame whose ‘on’ key is less than or equal to the left’s key.

**Comment by AlexyCz** [comment]
Response after the changes:
[response_1733261418281.json](https://github.com/user-attachments/files/17999630/response_1733261418281.json)
